const express = require('express');
const router = express.Router();
const authMiddleware = require('../../../middleware/auth.middleware');
const invoiceController = require('../controllers/invoice.controller');
const quoteController = require('../controllers/quote.controller');
const paymentController = require('../controllers/payment.controller');
router.use(authMiddleware);
router.get('/invoices', invoiceController.listInvoices);
router.get('/invoices/:id', invoiceController.getInvoice);
router.post('/invoices', invoiceController.createInvoice);
router.put('/invoices/:id', invoiceController.updateInvoice);
router.delete('/invoices/:id', invoiceController.deleteInvoice);
router.post('/invoices/:invoiceId/items', invoiceController.addInvoiceItem);
router.put('/invoices/:invoiceId/items/:itemId', invoiceController.updateInvoiceItem);
router.delete('/invoices/:invoiceId/items/:itemId', invoiceController.deleteInvoiceItem);
router.get('/invoices/:invoiceId/payments', paymentController.listPayments);
router.post('/invoices/:invoiceId/payments', paymentController.addPayment);
router.put('/payments/:id', paymentController.updatePayment);
router.delete('/payments/:id', paymentController.deletePayment);
router.get('/quotes', quoteController.listQuotes);
router.get('/quotes/:id', quoteController.getQuote);
router.post('/quotes', quoteController.createQuote);
router.put('/quotes/:id', quoteController.updateQuote);
router.delete('/quotes/:id', quoteController.deleteQuote);
router.post('/quotes/:id/convert', quoteController.convertToInvoice);
router.post('/quotes/:quoteId/items', quoteController.addQuoteItem);
router.put('/quotes/:quoteId/items/:itemId', quoteController.updateQuoteItem);
router.delete('/quotes/:quoteId/items/:itemId', quoteController.deleteQuoteItem);

module.exports = router;